language: ruby
dist: trusty
cache: bundler

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script: 
  - gem update --system
  - gem install bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-head
  - ruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
